name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Docker login
        run: echo ${{ secrets.DOCKER_AT }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - name: Docker Pull
        run: docker pull ${{secrets.DOCKER_LOGIN}}/scauth:latest

      - name: Drop oldest container
        run: docker rm -f scauth || true

      - name:  Create .env file
        run: echo "${{secrets.ENV}}" > $HOME/sc_auth.env

      - name: Run Container
        run: docker run -d --env-file $HOME/sc_auth.env --name sc-auth ${{secrets.DOCKER_LOGIN}}/scauth:latest

      - name: Remove .env file
        if: always()
        run: rm $HOME/sc_auth.env
