name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.10
  gotest:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: test
        run: go test -v ./...
  build:
    needs: [golangci, gotest]
    name: building the binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/scauth:latest .
      - name: docker login
        run: echo ${{ secrets.DOCKER_AT }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: docker push
        run: docker push ${{ secrets.DOCKER_LOGIN }}/scauth:latest